### ISSUE TITLE
[MIGRATION] Migrate from NextJS API App Router to ExpressJS Application

### ISSUE THREAD

**Issue by inclinedadarsh** [inclinedadarsh/timeloom-old#19]
## Tasks to do

- [x] Move all the code of Frontend into a new folder `client` that still works fine.
- [x] Create a new server folder in the root and create a basic server there
- [ ] #20
- [ ] #21
- [ ] #22
- [ ] Create a CI/CD Pipelines for deploying the server

## Development

This development is done in the migration branch. You can check out that branch you if you want to see all the work that has been done till yet.
The development is being done in the [migration branch](/inclinedadarsh/timeloom/tree/migration)

## Context

So a few days ago, in a community call with Dev, we talked that Timeloom should be based on a separate server for many reasons, and this is a result of such only.

## Contribution

If you want to contribute in this issue, you are very much welcome to join our discord server and let's discuss it there. Other than that, you can also use the [discussions](https://github.com/inclinedadarsh/timeloom/discussions) to present your views.
