### ISSUE TITLE
Todo list for next features

### ISSUE THREAD

**Issue by inclinedadarsh** [inclinedadarsh/timeloom-old#8]
- [ ] Add "Edit Profile Button"
- [ ] Add input fields to add new logs
- [ ] Add button to edit each log
- [ ] Add some placeholder to show when there is no name/bio etc.
